-- Supabase schema for Controlling OPK
create table if not exists public.costs (
  id bigint generated by default as identity primary key,
  Numer_dokumentu text,
  Data date not null,
  Nazwa text not null,
  Kwota numeric not null,
  ID_OPK text not null,
  inserted_at timestamp with time zone default now()
);

create index if not exists costs_data_idx on public.costs (Data);
create index if not exists costs_idopk_idx on public.costs (ID_OPK);

-- Optional: friendly names for OPK
create table if not exists public.opk_map (
  ID_OPK text primary key,
  Nazwa_OPK text
);
